### ISSUE TITLE
分辨问题

### ISSUE THREAD

**Issue by Peterpan0927** [sixstars/ctf#1]
需要将图片的分辨率做怎样的调整才会看到flag

**Comment by elnx** [comment]
请问你说的是哪道题？

**Comment by Peterpan0927** [comment]
我说的是可启动的磁盘那道题，谢谢，我现在已经解决了，是因为Linux下的图片查看器不会忽略错误的CRC校验码，因此用Linux打开修改过宽或高的png图片时，会出现打不开的情况。
